### ISSUE TITLE
419 (unknown status)

### ISSUE THREAD

**Issue by ustabasiibrahim** [alexusmai/vue-laravel-file-manager#10]
I'm getting this error when trying to load the file continuously, why?

![screenshot_1](https://user-images.githubusercontent.com/14348709/50834433-0b141180-1365-11e9-97f6-35203d426ff5.png)

**Comment by alexusmai** [comment]
Do you add csrf-token?

``

<meta name="csrf-token" content="{{ csrf_token() }}">
``

And check folder permissions, php params - upload_max_filesize, post_max_size

**Comment by ustabasiibrahim** [comment]
This is a SPA project. How to add token?

**Comment by alexusmai** [comment]
Put In to <head></head> block

**Comment by alexusmai** [comment]
> The VerifyCsrfToken middleware, which is included in the web middleware group, will automatically verify that the token in the request input matches the token stored in the session (Laravel docs)

Delete "web" middleware from laravel-filemanager config file

```
/**
     * Middleware
     * Add your middleware name to array -> ['web', 'auth', 'admin']
     * !!!! RESTRICT ACCESS FOR NON ADMIN USERS !!!!
     */
    'middleware'    => ['web', 'auth']
```
