### ISSUE TITLE
File Manager Not showing

### ISSUE THREAD

**Issue by codermjb** [alexusmai/vue-laravel-file-manager#11]
I tried for many hours each day and I am not able to get this to load.

I installed vue and vuex and put this in my app.js and also I installed the filemanager through node.

```
import Vue from 'vue';
import Vuex from 'vuex';
import FileManager from 'laravel-file-manager'
Vue.use(Vuex);
// create Vuex store, if you don't have it
const store = new Vuex.Store();
Vue.use(FileManager, {store});
```
I included bootstrap, app.js and app.css, font awesome and the file-manager tag. I added a web route as well. And I am getting a blank screen.

I was able to get vuejs working through the default laravel Component, but filemanager isn't loading for me.

I also ran npm run watch as well.

**Comment by alexusmai** [comment]
Hi. You can use the already compiled version in [package](https://github.com/alexusmai/laravel-file-manager), this npm package is needed in order to embed the file manager in your applications on Vue.js

And the settings that you show are not complete, it should be like this(If you use only file manager):

```
import Vue from 'vue';
import Vuex from 'vuex';
import FileManager from 'laravel-file-manager'

Vue.use(Vuex);

// create Vuex store, if you don't have it
const store = new Vuex.Store();

Vue.use(FileManager, {store});

window.fm = new Vue({
  el: '#fm',
  store,
  template: '<file-manager></file-manager>'
});
```

and view

```
<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<!-- Styles -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css>

 ....

<div class="container-fluid pb-3">
    <div class="row justify-content-center">
        <div class="col-10" style="height: 800px;">
            <div id="fm"></div>
        </div>
    </div>
</div>
...
<!-- File manager js -->
<script src="{{ asset('path/to/fm.js') }}"></script>
```

**Comment by codermjb** [comment]
Thank you for this. I have put this in there, but I am unable to find where we get the fm.js file from? I checked both repos out and I couldn't fine it.

**Comment by codermjb** [comment]
```
<link rel="stylesheet" href="{{ asset('vendor/file-manager/css/file-manager.css') }}">
<script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script>
```

Thank you for providing the extra config. That actually worked perfect for me! I am going to work on ACL's and permissions and I will let you know if I have other questions. And above was the scripts and CSS also required.
