### ISSUE TITLE
 ERROR  Failed to compile with 1 error                                                                                                            下午6:05:15   error  in ./node_modules/vue-loading-spinner/src/components/Texture.vue?vue&type=style&index=0&id=3d9bd062&lang=scss&scoped=true&  Syntax Error: TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by zhanghaifei1997** [alexusmai/vue-laravel-file-manager#113]
![1647943651(1)](https://user-images.githubusercontent.com/57278786/159456893-3447bacf-8eaf-426f-bc00-4e86c4f3a80b.jpg)

**Comment by alexusmai** [comment]
Hi, error in the vue-loading-spinner component, not in file-manager

**Comment by zhanghaifei1997** [comment]
> Hi, error in the vue-loading-spinner component, not in file-manager

Hello, as you saw, my project is a version of vue2, and css uses less. What regulations do to avoid some of these mistakes?
