### ISSUE TITLE
Base URL not working

### ISSUE THREAD

**Issue by xiaawan** [alexusmai/vue-laravel-file-manager#12]
Hi,
I have installed Laravel in sub directory. The base URL always goes to main site. 

This is my code in app.js

import Vue from 'vue';
import Vuex from 'vuex';
import FileManager from 'laravel-file-manager'

Vue.use(Vuex);

// create Vuex store, if you don't have it
const store = new Vuex.Store();

Vue.use(FileManager, {
    store, // required
    baseUrl: 'http://mysite.com/newplatform/public/file-manager/initialize',
});

window.fm = new Vue({
  el: '#fm',
  store,
  template: '<file-manager></file-manager>'
});

But it still hits the url "http://mysite.com/file-manager/initialize"

I have also set this in .env 

MIX_LFM_BASE_URL=http://mysite.com/newplatform/public/file-manager/initialize

But it's still not working. Can you please take a look?
Thanks

**Comment by alexusmai** [comment]
Hi. I checked it now and it works!
I get: 
> Request URL: http://mysite.com/newplatform/public/file-manager/initialize/initialize

Are you sure that you use your app.js ? Maybe in your view file you use compiled files from the /vendor folder ?
Show me your view file.

**Comment by xiaawan** [comment]
Hi, thanks for your reply.

Here is my view file.

@extends('adminlte::page')
@section('content')
<script src="{{ asset('js/app.js') }}" defer></script>
<link rel="stylesheet" href="{{ asset('vendor/file-manager/css/file-manager.css') }}">
<script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<div class="box">
	<div class="box-body">
		<div style="height: 600px;">
		    <div id="fm"><file-manager></file-manager></div>
		</div>
	</div>
</div>
@endsection

**Comment by alexusmai** [comment]
Yes, you use pre-compiled version from alexusmai/laravel-file-manger package

> <script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script> // delete this row!

You need create your application with your changes like baseUrl  
Use your app.js only!

Laravel documentation - [Compiling Assets](https://laravel.com/docs/5.7/mix)

**Comment by xiaawan** [comment]
Thanks, I will take a look.

**Comment by xiaawan** [comment]
Thanks for your help, I have deleted this line and it's working now.
`<script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script>`
