### ISSUE TITLE
Save cropped image not working

### ISSUE THREAD

**Issue by lkloon123** [alexusmai/vue-laravel-file-manager#15]
Hi, 
It shown save successfully but it not saved actually, the image still remain uncropped.

thanks for the great package btw 👍

**Comment by lkloon123** [comment]
**Addon**

it actually did saved, just because browser cached the image, so it remain.
any idea how to solve this problem?

Thanks

**Comment by alexusmai** [comment]
Hi, thanks.
As time appears free time, I will think how to fix it.
