### ISSUE TITLE
Directory selected by param (disk and path)

### ISSUE THREAD

**Issue by wiiwilasinee** [alexusmai/vue-laravel-file-manager#17]
Hi Dev master,
Is this library has anyway to selected default location of directory by using param disk and path ?

for example: if I set setting disk: diskA / path: directoryA/folderA, Can this app default at diskA/directoryA/folderA?

Thank you.

**Comment by alexusmai** [comment]
Hi.

You can use URL params only for setting the default disk

```
// !!! The disk must be in diskList !!!

// one window
http://site-name.com/your-url?leftDisk=public

// two windows
http://site-name.com/your-url?leftDisk=public&rightDisk=images
```
