### ISSUE TITLE
Dynamic update authorization token

### ISSUE THREAD

**Issue by Siarhei-Sudakou** [alexusmai/vue-laravel-file-manager#22]
How I can update authorization token after refresh?

**Comment by Siarhei-Sudakou** [comment]
I am using [websanova/vue-auth](https://github.com/websanova/vue-auth)

**Comment by alexusmai** [comment]
В новой версии параметры передаются через props-ы, должно помочь.

**Comment by Siarhei-Sudakou** [comment]
Огромное спасибо
