### ISSUE TITLE
Limit users actions

### ISSUE THREAD

**Issue by AdriEcobar** [alexusmai/vue-laravel-file-manager#24]
When you pass the contextMenu options I want to display the UI doesn't reflect them.
For example, I want my users to be able to copy or see the properties of the files. I pass the array with these options, but all the default options are still displayed 

```
Vue.use(FileManager, {
    store,
    contextMenu:[
        [], 
        [{"name":"copy","icon":"far fa-copy"}],
        [],
        [{"name":"properties","icon":"far fa-list-alt"}]
    ]
});
```

**Comment by alexusmai** [comment]
Hi,
There is no option "contextMenu", you can't change it.

**Comment by AdriEcobar** [comment]
Just if anyone else is interested this is how I changed all the options provided to the user:

`$store.state.fm.settings.contextMenu = [[{"name":"open","icon":"far fa-folder-open"},{"name":"audioPlay","icon":"fas fa-play"},{"name":"videoPlay","icon":"fas fa-play"},{"name":"view","icon":"fas fa-eye"},{"name":"edit","icon":"fas fa-file-signature"},{"name":"select","icon":"fas fa-check"},{"name":"download","icon":"fas fa-download"}],[{"name":"rename","icon":"far fa-edit"},{"name":"paste","icon":"far fa-clipboard"},{"name":"zip","icon":"far fa-file-archive"},{"name":"unzip","icon":"far fa-file-archive"}],[{"name":"delete","icon":"far fa-trash-alt text-danger"}],[{"name":"properties","icon":"far fa-list-alt"}]] ;`

**Comment by eserdinyo** [comment]
@AdriEcobar I'm getting this error when try to do this. Did this worked on you?

`[vuex] do not mutate vuex store state outside mutation handlers.`
