### ISSUE TITLE
Multi-select files

### ISSUE THREAD

**Issue by iusik** [alexusmai/vue-laravel-file-manager#25]
Is it possible to make multi-select files ?

**Comment by alexusmai** [comment]
Hi,
You can use -> ALT + LeftMouseBtn

**Comment by iusik** [comment]
It is not working. Checked on Mac OS and Windows =(

**Comment by alexusmai** [comment]
Ye, you are right, sorry... use Ctrl + LeftMouseBtn

**Comment by fibigerg** [comment]
Hi, this is not working for me, I tried every combination of key and mouse button. I am on Mac OS.

**Comment by jakimoff** [comment]
/vue-laravel-file-manager/src/components/manager/mixins/manager.js

![image](https://user-images.githubusercontent.com/17947003/112968746-41f8bc80-9155-11eb-9e24-bb16c8b06115.png)


Can you add that modify in your file, that work for MacOS

Or you may clone my modify repository [My fork & modify (Added Insert with $emit  && Multiselect for MacOS)](https://github.com/Galaxy-IT/vue-laravel-file-manager)
![image](https://user-images.githubusercontent.com/17947003/112951661-423c8c00-9144-11eb-9878-1ec6f01e2231.png)

**Comment by jakimoff** [comment]
@fibigerg write me please if it work for you

**Comment by jakimoff** [comment]
@alexusmai Can you add modify in your package for that?
