### ISSUE TITLE
TypeError: Cannot read property 'commit' of undefined

### ISSUE THREAD

**Issue by epik-web** [alexusmai/vue-laravel-file-manager#26]
![image](https://user-images.githubusercontent.com/51301949/61181295-20783a00-a62d-11e9-8c3d-c7b2ea5201f3.png)
![image](https://user-images.githubusercontent.com/51301949/61181298-3554cd80-a62d-11e9-9fa7-f4981c99ac49.png)
![image](https://user-images.githubusercontent.com/51301949/61181314-5d443100-a62d-11e9-83ab-1f28f84ad01f.png)
When I create brand new store it works, but with my store it doesnt work, why ?

**Comment by emtiazzahid** [comment]
Is this solved ?

**Comment by alexusmai** [comment]
I cannot repeat this error, it works for me

**Comment by sanpakyou027** [comment]
@alexusmai I'm also encountering this error, may i know what version vue and vuex did you use?


Please see attachment 
![chrome_NqKuSHBfNY](https://user-images.githubusercontent.com/4095416/65104175-24488400-da03-11e9-9a59-89d8a5bc2e99.png)
![Code_xNrMlmY8ZY](https://user-images.githubusercontent.com/4095416/65104177-24488400-da03-11e9-9b8c-0fcd4b854767.png)
![Code_Xp9ASktc30](https://user-images.githubusercontent.com/4095416/65104219-51953200-da03-11e9-8463-e00dd594b6b9.png)

**Comment by sanpakyou027** [comment]
@alexusmai  i resolve the issue by adding the store on the vue instance 

By the way nice library :) 👍 
![chrome_Ou4lmmPiKR](https://user-images.githubusercontent.com/4095416/65104842-84402a00-da05-11e9-9cc3-807e2c0f26f5.png)
![Code_c3J9EChCMc](https://user-images.githubusercontent.com/4095416/65104845-84d8c080-da05-11e9-95a3-a1f42fa7a3f0.png)
