### ISSUE TITLE
A technique question

### ISSUE THREAD

**Issue by hakhsin** [alexusmai/vue-laravel-file-manager#27]
Hi my friend, I am trying to create my own file manager. But I have no any experience in this job. I look at on your code for take an insight but I didn't know how you parse json for show file or folders. In other words, I want to know what object do you get from back-end? And, how do you parse it? Example:
You get from server:
```json
{
"picture" : 
  {
    "old": {"type":"dir","url":"www.example.con/..."},
    "image1":{"type": "jpeg", "url": "..."},
  }
}
```
On front-end:
```javaScript
directories= this.getDirectories();
for ([name, desc] of directories) {
  //handling
} 
```
Is your app algorithm like this? Or, are there a better way?

**Comment by alexusmai** [comment]
Hi. I get from server:

```
{
  directories: [
    {type: "dir", path: "images/nature", timestamp: 1562422432, dirname: "images", basename: "nature", acl: 2},
    ....,
  ],
  files: [
    {
      acl: 2, basename: "logo.bmp", dirname: "images", extension: "bmp", filename: "logo", path: "images/logo.bmp", size: 1843254, timestamp: 1561899210, type: "file"
    },
    ....,
  ],
}
```

> Is your app algorithm like this? Or, are there a better way?

Yes, I show directories and files using the "for" loop

**Comment by hakhsin** [comment]
Thank you my friend.
