### ISSUE TITLE
Dblclick to select file

### ISSUE THREAD

**Issue by MWStudio4** [alexusmai/vue-laravel-file-manager#29]
Is there settings to got selected file after dblclick instead of view it?

**Comment by alexusmai** [comment]
No, what do you need to do?

**Comment by MWStudio4** [comment]
IMHO dblclick to select file and close filemanager is more general behavior within media managers.
Now dblclick opens preview window with file. I'm using filemanager to select file for featured image. I include filemanager into bootstrap-vue modal box with callback.

`this.$store.commit('fm/setFileCallBack', url => {
      console.info(`File choosen!!! - ${url}`)
      this.onSelectFile()
    })`

 To say the truth the first time after open modal window dblclick calls callback function. But only one time. After that dblclick opens preview. I think  the reason is in vuex store where active selected file stays after closing bootstrap modal. May be i could clear this somehow ?

**Comment by alexusmai** [comment]
I think I know where is the problem.. 
You use bootstrap-vue, it's mean - modal content destroy every moment when you close the modal window.. This calls a method that clears the FM state. 

You will need to set a callback for FM every time you show a modal window. 

Or try to make the modal window static - (read this)[https://bootstrap-vue.js.org/docs/components/modal#lazy-loading-and-static-modals] -I'm not sure if this will work, but you can try.

**Comment by MWStudio4** [comment]
You are right! Thank you. Add static prop to bootstrap modal solved the problem.
