### ISSUE TITLE
vue-laravel-file-manager license ?

### ISSUE THREAD

**Issue by Xyrop** [alexusmai/vue-laravel-file-manager#32]
Hello !

The license to laravel-file-manager is MIT, but there doesn't seem to be any license to vue-laravel-file-manager. To all intents, vue-laravel-file-manager seems proprietary right now.
Is it the same license as laravel-file-manager ? Or is it governed by another license ? Thanks for your clarification.

Best regards !

Xyrop

**Comment by alexusmai** [comment]
Hi, yes, it's the same license - MIT
