### ISSUE TITLE
How to make multiple managers

### ISSUE THREAD

**Issue by mgarcia96** [alexusmai/vue-laravel-file-manager#36]
Hey, I saw that I can configurate more than one Disk, but I want to make it individualy, Ex: 
3 disks, 3 diferent pages (and manager)

How can I do that?

Thx!

**Comment by alexusmai** [comment]
Hi,

You can use [dynamic configuration](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/configuration.md#dynamic-configuration)

Something like this (example)

```
/**
     * Get disk list
     *
     * ['public', 'local', 's3']
     *
     * @return array
     */
    public function getDiskList(): array
    {
         if (request()->routeIs('route.name')) {
            return ['public'];
        } elseif (request()->routeIs('route.another name')) {
            return ['local'];
        }
        
    }
```
