### ISSUE TITLE
Empty filename

### ISSUE THREAD

**Issue by et-nik** [alexusmai/vue-laravel-file-manager#4]
Some files have empty filename (.gitignore, .env, .htaccess, etc.)
![screenshot-gameap3 local-2018 11 16-17-15-59](https://user-images.githubusercontent.com/3670640/48626727-b5099a00-e9c3-11e8-8f5b-ea424262c444.png)

Maybe change filename to basename? I think it looks better.
![screenshot-gameap3 local-2018 11 16-17-20-06](https://user-images.githubusercontent.com/3670640/48626779-e2eede80-e9c3-11e8-951a-944d3c5ca871.png)

**Comment by alexusmai** [comment]
Hi, good idea, added to task list
