### ISSUE TITLE
Need help for develop vue on package

### ISSUE THREAD

**Issue by vahidalvandi** [alexusmai/vue-laravel-file-manager#40]
I resntly used your file manage it is awesome and very good. I work with vue in self project . I need help . When i use vue in packages laravel i create app in this path and conenct it to main webpack it work but i think is not good method for develop.

What is your idea for use vue in packages in laravel and create prod version like your file manager.

Thank you very much

**Comment by alexusmai** [comment]
I think you don't need to make a separate application, unless you are going to reuse it.
