### ISSUE TITLE
have error 500 in same images

### ISSUE THREAD

**Issue by vahidalvandi** [alexusmai/vue-laravel-file-manager#41]
`[2019-12-02 16:49:00] local.ERROR: Unable to init from given binary data. {"userId":8,"exception":"[object] (Intervention\\Image\\Exception\\NotReadableException(code: 0): Unable to init from given binary data. at /media/pc3/projects/laravel/master/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php:115)`

**Comment by alexusmai** [comment]
I don't know where is the problem.. maybe file/folder permissions
