### ISSUE TITLE
Empty response from this.$store.dispatch('fm/upload'

### ISSUE THREAD

**Issue by Flavier** [alexusmai/vue-laravel-file-manager#42]
Hi. I init your app in my resources/js/app.js :
`
window.Vue = require('vue');
import Vuex from 'vuex';
import FileManager from 'laravel-file-manager'

//Registration FileManager component
Vue.use(Vuex);
const store = new Vuex.Store();
Vue.use(FileManager, {store});

const app = new Vue({
    el: '#app',
    store:store
});
`

FileManager loaded ok. But when I try upload some image I get response:

app.js:86753 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined`

I debug it in:
`    
uploadFiles() {
      // if files exists
      if (this.countFiles) {
        // upload files
        this.$store.dispatch('fm/upload', {
          files: this.newFiles,
          overwrite: this.overwrite,
        }).then((response) => {
            console.log(response);
          // if upload is successful
          if (response.data.result.status === 'success') {
            // close modal window
            this.hideModal();
          }
        });
      }
    },
`
in Upload.vue
I missed something? Thank you for yours sugestions.

**Comment by alexusmai** [comment]
Hi,

Only upload doesn't work? Did you see laravel logs? Maybe you have some folder permissions issue.
What does the  "upload" request return? (go to browser console -> network tab)

**Comment by Flavier** [comment]
Hi. 
Yes I have trouble with upload. 
My error responde message is:
message: "Argument 1 passed to Spatie\HttpLogger\DefaultLogWriter::Spatie\HttpLogger\{closure}() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, array given"

**Comment by Flavier** [comment]
Problem solved with new version of:
[https://github.com/spatie/laravel-http-logger/releases/tag/1.4.0](url)
