### ISSUE TITLE
Can't resolve 'scss-loader' 

### ISSUE THREAD

**Issue by edwinjerez** [alexusmai/vue-laravel-file-manager#49]
Using Vue 2.6.10.
Vuex 2.1.1
Webpack 1.14.0

after I import FileManager in app.js like below and run gulp, 
import FileManager from 'laravel-file-manager';

I got the following error.

![image](https://user-images.githubusercontent.com/29590370/73243545-cf075500-41e2-11ea-93a3-3188b5ce6485.png)
Are there any recommendations?
Thank you.

**Comment by alexusmai** [comment]
Hi,
try to install:

```
npm install sass-loader node-sass --save-dev
```
