### ISSUE TITLE
Vuex Error

### ISSUE THREAD

**Issue by erencan** [alexusmai/vue-laravel-file-manager#5]
```
import FileManager from 'laravel-file-manager'
import Vuex from 'vuex'

Vue.use(Vuex)

const store = new Vuex.Store()

Vue.use(FileManager, {store})
```
We are getting Vuex error when initialize new Vuex store.

`vuex.esm.js?358c:97 Uncaught Error: [vuex] getters should be function but "getters.fm/diskList" in module "fm" is [].`

**Comment by alexusmai** [comment]
Thanks, fixed

**Comment by kevinspooner** [comment]
I have the same error Today, How i can fix this?
