### ISSUE TITLE
Как добавить выбор файла в модальном окне?

### ISSUE THREAD

**Issue by maksakoviliya** [alexusmai/vue-laravel-file-manager#51]
Добрый день! Отличный файл менеджер! Спасибо за него)
Как открыть файл менеджер в модальном окне? И чтобы была возможность выбора файла? И как отследить событие выбора файла? Но сделать это внутри компонента vue...

**Comment by maksakoviliya** [comment]
![image](https://user-images.githubusercontent.com/16371638/73608861-faba7e80-45d8-11ea-9728-b178cc220b1c.png)
Вот в таком модальном окне, при правом клике, нет даже пункта Select

**Comment by maksakoviliya** [comment]
<template>
  <div>
    <button class="btn btn-outline-secondary" 
            type="button"
            data-toggle="modal"
            data-target="#fileUploaderModal"
          >Select</button>
    <div class="modal fade bd-example-modal-lg" tabindex="-1" id="fileUploaderModal" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <file-manager></file-manager>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default { 
    
  }
</script>

**Comment by maksakoviliya** [comment]
`<template>
  <div>
    <button class="btn btn-outline-secondary" 
            type="button"
            data-toggle="modal"
            data-target="#fileUploaderModal"
          >Select</button>
    <div class="modal fade bd-example-modal-lg" tabindex="-1" id="fileUploaderModal" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <file-manager></file-manager>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default { 
    
  }
</script>`

**Comment by maksakoviliya** [comment]
![image](https://user-images.githubusercontent.com/16371638/73609016-8aacf800-45da-11ea-9b67-acf826613620.png)

**Comment by alexusmai** [comment]
Добрый день, спасибо.
Чтобы появился select вам нужно передать файловому менеджеру функцию которая будет вызываться при выборе файла, например как [тут](https://github.com/alexusmai/laravel-file-manager/blob/master/resources/views/fmButton.blade.php)
В эту функцию первым и единственным параметром будет передана ссылка на выбранный файл, ну и плюс вы можете вызвать нужные вам действия.
Если файл менеджер используется не только для выбора изображении не забудьте обнулить  параметр fileCallback после выбора изображения.

**Comment by maksakoviliya** [comment]
Благодарю за ответ, но, видимо, я  туповат,  не понимаю где прописать эту функцию))
Вот блок кода, который отвечает за вывод Вашего файл менеджера. Есть мой компонент, внутри которого модальное окно бутсрап, вызывается jquery (Не уверен что это хорошо, но повторюсь, туповат)). В том примере, который Вы скинули - есть $emmit функции, указанной в opener. Т.е. при selecte - вызывается функция. А как передать эту функцию из компонента??? Еще раз благодарю! Вы сделали очень крутую вещь!

```javascript
<template>
  <div>
    <button class="btn btn-outline-secondary" 
            type="button"
            data-toggle="modal"
            data-target="#fileUploaderModal"
          >Select</button>
    <div class="modal fade bd-example-modal-lg" tabindex="-1" id="fileUploaderModal" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <file-manager></file-manager>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default { 
    
  }
</script>
```

**Comment by maksakoviliya** [comment]
Есть у кого мысли?)

**Comment by alexusmai** [comment]
Примерно так:

```
<template>

    <div class="container">

        <!-- Button trigger modal -->
        <button v-on:click="show()" type="button" class="btn btn-primary">
            Launch demo modal
        </button>

        <!-- Modal -->
        <div class="modal fade bd-example-modal-xl" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-xl" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div style="height: 600px;">
                            <file-manager></file-manager>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        methods: {
            show() {
                $('#exampleModal').modal('show');

                // set callback
                this.$store.commit('fm/setFileCallBack', url => {
                    // use the file url
                    console.info(`File chosen!!! - ${url}`);
                    // close modal window
                    $('#exampleModal').modal('hide');
                });
            },
        },
    };
</script>
```

вместо console.info делаете что вам необходимо с  полученным url

**Comment by maksakoviliya** [comment]
Спасибо Вам огромное! Именно то, что нужно!!
