### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by guysolamour** [alexusmai/vue-laravel-file-manager#53]
Hello, how to implement this package in a  laravel application with the laravel filemanager created by the same author.

**Comment by alexusmai** [comment]
> This package is working so good in my application. I use the default js file included in this package but wheb I load vue js and my own components it is not working.

How to fix it or how can I use the vue front package

Hi,

In your application:

```
import Vue from 'vue';
import Vuex from 'vuex';
import FileManager from 'laravel-file-manager';
import Test from 'TestComponent';

Vue.use(Vuex);

// create Vuex store, if you don't have it
const store = new Vuex.Store();

Vue.use(FileManager, {store});

new Vue({
  el: '#fm',
  store,
  template: '<test></test>',
});
```

TestComponent.vue

```
<template>
    <div>
        <file-manager></file-manager>
    </div>
</template>

<script>
  export default {
    name: 'Test',
  }
</script>
```
