### ISSUE TITLE
base url issue

### ISSUE THREAD

**Issue by chaithanyanbs** [alexusmai/vue-laravel-file-manager#65]
I have configured my base url 
as MIX_LFM_BASE_URL=http://localhost:8080/blog.
But while loading the page the ajax request for initialization calling to 
this 'http://localhost/file-manager/initialize 404 (Not Found)'

Did I miss anything?

**Comment by alexusmai** [comment]
Hi,
It work's when you compile your vue application(with LFM), not when you'are using pre-compiled js
