### ISSUE TITLE
it can't using in vue project.

### ISSUE THREAD

**Issue by taoyonggang** [alexusmai/vue-laravel-file-manager#66]
use the projec at vue. will throw error:

[Vue warn]: Error in render: "TypeError: Cannot read property 'back' of undefined"

found in

---> <Navbar> at node_modules/laravel-file-manager/src/components/blocks/Navbar.vue
       <FileManager> at node_modules/laravel-file-manager/src/FileManager.vue
         <Index> at src/views/cloud/FileManager/index.vue
           <AppMain> at src/layout/components/AppMain.vue
             <Layout> at src/layout/index.vue
               <App> at src/App.vue
                 <Root>

This is the vue page.

<template>
  <file-manager v-bind:settings="settings"></file-manager>
</template>

<script>

export default {
  data() {
    return {
      settings: {
        // axios headers
        headers: {
          'X-Requested-With': 'XMLHttpRequest',
          Authorization: `Bearer ${window.localStorage.getItem('user-token')}` },
        baseUrl: 'http://localhost:8013/api/cloud/cloudDiskFileInfo/',
        windowsConfig: 2,
        lang: 'zh_CN',
        translation: {
          name: 'zh_CN',
          content: {
            about: '关于',
            back: '后退'
          }
        }
      }
    }
  }
}
</script>

**Comment by alexusmai** [comment]
- your variant - 'zh_CN'
- need to change to - 'zh-CN'
