### ISSUE TITLE
Beginner with npm I have problem to setup your package in a default laravel project

### ISSUE THREAD

**Issue by GregoireSailland** [alexusmai/vue-laravel-file-manager#7]
### app.js
====================================================
require('./bootstrap');

window.Vue = require('vue');
import Vue from 'vue';
import Vuex from 'vuex';
import FileManager from 'laravel-file-manager';

Vue.use(Vuex);

// create Vuex store, if you don't have it
const store = new Vuex.Store();

Vue.use(FileManager, {store});
/**
 * The following block of code may be used to automatically register your
 * Vue components. It will recursively scan this directory for the Vue
 * components and automatically register them with their "basename".
 *
 * Eg. ./components/ExampleComponent.vue -> <example-component></example-component>
 */

Vue.component('example-component', require('./components/ExampleComponent.vue'));

// const files = require.context('./', true, /\.vue$/i)
// files.keys().map(key => Vue.component(key.split('/').pop().split('.')[0], files(key)))

/**
 * Next, we will create a fresh Vue application instance and attach it to
 * the page. Then, you may begin adding components to this application
 * or customize the JavaScript scaffolding to fit your unique needs.
 */

const app = new Vue({
    el: '#app'
});

=======================================================

### C:\laragon\www\homestead>npm run dev

> @ dev C:\laragon\www\homestead
> npm run development

> @ development C:\laragon\www\homestead
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting

 ERROR  Failed to compile with 1 errors                                                                         16:18:20

 error  in ./node_modules/laravel-file-manager/src/components/blocks/Notification.vue

(Emitted value instead of an instance of Error)
  Error compiling template:

  <div class="fm-notification">
      <transition-group name="notify">
          <div class="fm-notification-item" role="alert"
               v-for="(notification, index) in notifications"
               v-bind:class="`fm-${notification.status}`"
               v-bind:key="index">
              {{ notification.message }}
          </div>
      </transition-group>
  </div>

  - Do not use v-for index as key on <transition-group> children, this is the same as not using keys.

 @ ./node_modules/laravel-file-manager/src/components/blocks/Notification.vue 10:23-242
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/laravel-file-manager/src/FileManager.vue
 @ ./node_modules/laravel-file-manager/src/FileManager.vue
 @ ./node_modules/laravel-file-manager/src/init.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
                                                                                                                  Asset    Size  Chunks                    Chunk Names
  /js/app.js  2.9 MB       0  [emitted]  [big]  /js/app
/css/app.css  214 kB       0  [emitted]         /js/app

ERROR in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-dc07b964","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./node_modules/laravel-file-manager/src/components/blocks/Notification.vue
(Emitted value instead of an instance of Error)
  Error compiling template:

  <div class="fm-notification">
      <transition-group name="notify">
          <div class="fm-notification-item" role="alert"
               v-for="(notification, index) in notifications"
               v-bind:class="`fm-${notification.status}`"
               v-bind:key="index">
              {{ notification.message }}
          </div>
      </transition-group>
  </div>

  - Do not use v-for index as key on <transition-group> children, this is the same as not using keys.

 @ ./node_modules/laravel-file-manager/src/components/blocks/Notification.vue 10:23-242
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/laravel-file-manager/src/FileManager.vue
 @ ./node_modules/laravel-file-manager/src/FileManager.vue
 @ ./node_modules/laravel-file-manager/src/init.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\grego\AppData\Roaming\npm-cache\_logs\2018-12-22T15_18_21_112Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\grego\AppData\Roaming\npm-cache\_logs\2018-12-22T15_18_21_150Z-debug.log

C:\laragon\www\homestead>

**Comment by alexusmai** [comment]
Yes, the problem came with a new version of Vue, fixed .. update package and try.
