### ISSUE TITLE
Update Axios

### ISSUE THREAD

**Issue by MarioPerini** [alexusmai/vue-laravel-file-manager#77]
# npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
No fix available
node_modules/laravel-file-manager/node_modules/axios
  laravel-file-manager  *
  Depends on vulnerable versions of axios
  node_modules/laravel-file-manager

**Comment by alexusmai** [comment]
done
