### ISSUE TITLE
Vue component not recognizing store: Cannot read property 'commit' of undefined

### ISSUE THREAD

**Issue by daydevelops** [alexusmai/vue-laravel-file-manager#82]
I am getting this error in my javascript console:

```
Cannot read property 'commit' of undefined
```

The `$store` property on the component seems to be undefined. I have followed the instructions for installation of both the front end package and back end package closely but I cannot see why I am getting this error.

Here is my app.js for my laravel project:

```
window.Vue = require('vue').default; // I also tried using "import Vue from 'Vue'" like the instructions specify
... 
import Vuex from 'Vuex';
import FileManager from 'laravel-file-manager';
Vue.use(Vuex);
const store = new Vuex.Store();

Vue.use(FileManager, {store});
```

My config/file-manager.php is the default setup that was given.

I am using laravel's webpack to compile my assets.
![image](https://user-images.githubusercontent.com/38594177/114555288-1c35e200-9c42-11eb-9e2f-9a45828c7a73.png)
![image](https://user-images.githubusercontent.com/38594177/114555328-27890d80-9c42-11eb-88d7-d739a19c42e6.png)

**Comment by iwasherefirst2** [comment]
Does https://github.com/alexusmai/vue-laravel-file-manager/issues/37 help?

**Comment by daydevelops** [comment]
Yep, adding the store to this part fixed it:

```
const app = new Vue({
  store,
  el: '#app',
  template: '<example-component></example-component>',
});
```
